# This is a basic workflow to help you get started with Actions

name: deploy_docs

on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: ln -s ../docs/mkdocs.yml ../mkdocs.yml
      - run: mkdocs gh-deploy --force
